package festivalOrt_ParcialFDP;

public enum Resultado {
	
	COMPRA_REALIZADA, ESCENARIO_LLENO, ENTRADAS_FESTIVAL_AGOTADAS, PARTICIPANTE_INEXISTENTE, PARTICIPANTE_CON_ENTRADA_PREVIA, BANDA_EXISTENTE_EN_OTRO_ESCENARIO, BANDA_EXISTE_EN_ESCENARIO_ELEGIDO, ESCENARIO_INEXISTENTE, REGISTRO_OK
	
}
